# travis configuration file
# Copyright 2018 Ilya Shipitsin <chipitsine@gmail.com>
#                Nicolas Mora <mail@babelouest.org>
sudo: required
language: c
addons:
  apt:
    packages: [ check, libsubunit-dev, cppcheck, pkg-config ]
matrix:
  include:
    - env: LABEL=linux-gcc
      os: linux
      compiler: gcc
    - env: LABEL=linux-clang
      os: linux
      compiler: clang
    - env: LABEL=osx
      os: osx
      addons:
        homebrew:
          packages:
          - check
          - pkg-config
          update: true
      script:
        - mkdir build && cd build
        - cmake -DBUILD_YDER_TESTING=on -DWITH_JOURNALD=off ..
        - make test
    - env: LABEL=cppcheck
      os: linux
      script:
        - cppcheck --force --enable=warning,missingInclude --error-exitcode=1 . >build.log 2>&1 || (cat build.log && exit 1)
script:
  - mkdir build && cd build
  - cmake -DBUILD_YDER_TESTING=on -DWITH_JOURNALD=off ..
  - make test package
  - sudo make install
  - cd ../
  - make Y_DISABLE_JOURNALD=1
  - make check
