on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config check libsubunit-dev cppcheck libsystemd-dev doxygen
    - name: cppcheck
      run: cppcheck --force --enable=warning,missingInclude --error-exitcode=1 .
    - name: dependencies
      run: |
        cd /opt
        git clone https://github.com/babelouest/orcania.git
        mkdir build
        cd build
        
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib ../orcania
        make
        sudo make install
        rm -rf *
    - name: build
      run: |
        mkdir build
        cd build
        cmake -DBUILD_YDER_TESTING=on -DBUILD_YDER_DOCUMENTATION=on ..
        make test package doc
        sudo make install
        sudo ldconfig
        cd ..
        make
        make clean check
